### PR TITLE
Export to block JSON

### LINKED ISSUE #74: Export To JSON
For resource pack creators.

### PR DESCRIPTION
**Pull request by fredtargaryen**
Should output a block JSON that corresponds exactly to the Tabula model view, if the model is built around (0, 0, 0). I have used it to create a block for my own mod, containing 50 cubes and different rotations. Also includes an error window with information on what data was invalid.

(Closes #74 )

### CODE REVIEW

**Comment by iChun** [comment]
Only managed to get a look at this now. You've accidentally committed some production files along with the PR. Mind clearing those out and squashing your commits then this should be good to pull.

**Comment by fredtargaryen** [comment]
Sorry about that, I got rid of them. And you want me to squash the whole branch?

**Comment by iChun** [comment]
Yep, squash it all so it's one nice commit. I'll be able to pull it in
after that.

**Comment by fredtargaryen** [comment]
Is this ok?

**Comment by iChun** [comment]
Yep, looks good. I'll push it out for the next update. Thanks so much for this!

**Pull request merged**
